from pathlib import Path
import csv
import re


POST_DIRS = ("_writing", "_building", "_notes", "_marginalia")
TAG_DIR = Path("tag")
GENERATED_MARKER = "# generated by scripts/sync_tag_pages.py"


def slugify(value):
    value = value.strip().lower()
    value = re.sub(r"[^\w]+", "-", value, flags=re.UNICODE)
    value = value.replace("_", "-")
    return value.strip("-")


def titleize(tag):
    if tag.lower() == "ml":
        return "ML"

    return " ".join(part.capitalize() for part in tag.split())


def clean_value(value):
    return value.strip().strip("'\"")


def parse_inline_list(value):
    value = value.strip()
    if not (value.startswith("[") and value.endswith("]")):
        return []

    inner = value[1:-1].strip()
    if not inner:
        return []

    return [
        clean_value(item)
        for item in next(csv.reader([inner], skipinitialspace=True))
        if clean_value(item)
    ]


def extract_front_matter(text):
    if not text.startswith("---\n"):
        return ""

    end = text.find("\n---\n", 4)
    if end == -1:
        return ""

    return text[4:end]


def extract_tags(front_matter):
    lines = front_matter.splitlines()

    for index, line in enumerate(lines):
        match = re.match(r"^tags:\s*(.*)$", line)
        if not match:
            continue

        inline_tags = parse_inline_list(match.group(1))
        if inline_tags:
            return inline_tags

        tags = []
        for child in lines[index + 1 :]:
            if child and not child.startswith((" ", "\t")):
                break

            item = re.match(r"^\s*-\s*(.+?)\s*$", child)
            if item:
                tags.append(clean_value(item.group(1)))

        return tags

    return []


def collect_tags():
    tags = set()

    for post_dir in POST_DIRS:
        for path in Path(post_dir).glob("*.md"):
            front_matter = extract_front_matter(path.read_text(encoding="utf-8"))
            for tag in extract_tags(front_matter):
                if tag:
                    tags.add(tag)

    return sorted(tags, key=lambda item: item.lower())


def tag_page(tag):
    escaped_tag = tag.replace('"', '\\"')
    return f"""---
layout: tag
title: {titleize(tag)}
tag: "{escaped_tag}"
---
{GENERATED_MARKER}
"""


def sync_tags():
    TAG_DIR.mkdir(exist_ok=True)
    desired_paths = set()

    for tag in collect_tags():
        slug = slugify(tag)
        if not slug:
            continue

        path = TAG_DIR / f"{slug}.md"
        desired_paths.add(path)
        path.write_text(tag_page(tag), encoding="utf-8")

    for path in TAG_DIR.glob("*.md"):
        if path in desired_paths:
            continue
        if GENERATED_MARKER in path.read_text(encoding="utf-8"):
            path.unlink()


if __name__ == "__main__":
    sync_tags()
